import type { Metadata } from "next";
import { Google_Sans_Flex, Quicksand } from "next/font/google";
import "./globals.css";

const googleSans = Google_Sans_Flex({
    variable: "--font-google-sans-flex",
    subsets: ["latin"]
})

const quicksand = Quicksand({
    variable: "--font-quicksand",
    subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${googleSans.variable} ${quicksand.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
